支持5个老旧的SM2相关函数
Tongsuo-Project/Tongsuo pull request #11
Opened 2022-05-30 07:47 UTC by InfoHunter

There are five SM2 related legacy APIs existed in old BabaSSL version,
this commit makes them usable in Tongsuo to keep the compatibility, this
commit makes them usable in Tongsuo to keep the compatibility.

##### Checklist

- [ ] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-05-30 08:04 UTC, jinjiu approved these changes
LGTM

2022-05-31 06:18 UTC, dongbeiouba requested changes
CI failed

2022-06-07 04:01 UTC, InfoHunter commented
Fixed

2022-06-07 07:26 UTC, dongbeiouba approved these changes
LGTM

2022-06-07 08:27 UTC, InfoHunter commented
CIs are happy now

2022-06-07 08:33 UTC, merged