Add support for asynchronous session lookup
Tongsuo-Project/Tongsuo pull request #15
Opened 2022-06-04 15:28 UTC by jinjiu

Reference: https://github.com/openssl/openssl/pull/1588

##### Checklist

- [x] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-06-07 02:31 UTC, InfoHunter commented
有几个CI失败了

2022-06-08 09:04 UTC, dongbeiouba commented on ssl/statem/statem.h
> + *
多余的注释

2022-06-08 09:13 UTC, dongbeiouba commented on test/recipes/90-test_babasslapi.t
>  (undef, my $tmpfilename) = tempfile();
$tmpfilename 没用就删除吧

2022-06-08 09:18 UTC, dongbeiouba commented on test/babasslapitest.c
> +    ADD_TEST(test_babassl_api);
老的test_babassl_api()太复杂，已经重构成上面的多个小的单独的测试用例，比如SSL_get0_alpn_proposed()接口已经在test_babassl_get0_alpn_proposed()中测试过了，可以增加测试session lookup相关接口测试函数，例如test_babassl_session_lookup()，而不是test_babassl_api()

2022-06-09 10:07 UTC, jinjiu commented on test/babasslapitest.c
> +    ADD_TEST(test_babassl_api);
> 老的test_babassl_api()太复杂，已经重构成上面的多个小的单独的测试用例，比如SSL_get0_alpn_proposed()接口已经在test_babassl_get0_alpn_proposed()中测试过了，可以增加测试session lookup相关接口测试函数，例如test_babassl_session_lookup()，而不是test_babassl_api()
已修复

2022-06-10 03:41 UTC, dongbeiouba requested changes

2022-06-10 03:41 UTC, dongbeiouba commented on ssl/statem/statem_srvr.c
> +    }
单条语句不用加花括号

2022-06-10 05:50 UTC, jinjiu commented on ssl/statem/statem_srvr.c
> +    }
> 单条语句不用加花括号

已修复

2022-06-11 03:06 UTC, InfoHunter approved these changes

2022-06-11 03:06 UTC, merged