Add an api to support skip SCSV
Tongsuo-Project/Tongsuo pull request #16
Opened 2022-06-05 02:23 UTC by jinjiu

##### Checklist

- [x] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-06-07 02:28 UTC, InfoHunter commented on util/libssl.num
> +SSL_set_skip_scsv                       ?	3_0_3	EXIST::FUNCTION:SKIP_SCSV
没make renumber

2022-06-08 09:25 UTC, dongbeiouba requested changes

2022-06-08 09:25 UTC, dongbeiouba commented on doc/man3/SSL_set_skip_scsv.pod
> +L<https://www.openssl.org/source/license.html>.
忘记删除

2022-06-10 03:43 UTC, dongbeiouba approved these changes
LGTM

2022-06-10 04:57 UTC, InfoHunter approved these changes

2022-06-10 04:57 UTC, merged