Support BoringSSL QUIC API, draft-ietf-quic-transport-34
Tongsuo-Project/Tongsuo pull request #18
Opened 2022-06-08 03:45 UTC by jinjiu

##### Checklist

- [x] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-06-10 03:24 UTC, dongbeiouba requested changes
ntls_extensions.c中的ext_defs也需要修改，因为增加了quic相关的扩展

2022-06-10 03:24 UTC, dongbeiouba commented on test/build.info
> +          provfetchtest prov_config_test rand_test babasslapitest quicapitest
建议增加判断，!$disabled{'quic'}的时候才有quicapitest

2022-06-10 03:24 UTC, dongbeiouba commented on test/build.info
> +  SOURCE[quicapitest]=quicapitest.c helpers/ssltestlib.c
同上，建议增加判断，!$disabled{'quic'}的时候才有

2022-06-10 03:24 UTC, dongbeiouba commented on test/recipes/90-test_quicsslapi.t
> +    if alldisabled(grep { $_ ne "ssl3" } available_protocols("tls"));
需要增加判断，如果disable quic就跳过

2022-06-10 03:24 UTC, dongbeiouba commented on test/quicapitest.c
> +#if !defined(OPENSSL_NO_QUIC) && !defined(OSSL_NO_USABLE_TLS1_3)
建议在构建的时候判断，build info 中，如果disable quic，就不编译quicapitest；
测试的时候根据判断，进行跳过。

2022-06-10 05:24 UTC, InfoHunter commented on doc/man3/SSL_CTX_set_quic_method.pod
> +SSL_is_quic() indicates whether a connection uses QUIC.  A given B<SSL>
没多空格，我记得pod文件就是句号之后是2个空格

2022-06-10 06:29 UTC, jinjiu commented
> ntls_extensions.c中的ext_defs也需要修改，因为增加了quic相关的扩展

ntls 需要 quic 么？

2022-06-10 06:46 UTC, jinjiu commented on doc/man3/SSL_CIPHER_get_name.pod
> +SSL_CIPHER_get_prf_nid() retuns the pseudo-random function NID for B<c>. If B<c> is
> returns

已修复

2022-06-10 06:48 UTC, jinjiu commented on test/recipes/90-test_quicsslapi.t
> +    if alldisabled(grep { $_ ne "ssl3" } available_protocols("tls"));
> 需要增加判断，如果disable quic就跳过

已改

2022-06-10 06:48 UTC, jinjiu commented on test/build.info
> +  SOURCE[quicapitest]=quicapitest.c helpers/ssltestlib.c
> 同上，建议增加判断，!$disabled{'quic'}的时候才有

已改

2022-06-10 06:48 UTC, jinjiu commented on test/build.info
> +          provfetchtest prov_config_test rand_test babasslapitest quicapitest
> 建议增加判断，!$disabled{'quic'}的时候才有quicapitest

已改

2022-06-10 06:49 UTC, jinjiu commented on doc/man3/SSL_CTX_set_quic_method.pod
> +SSL_get_peer_quic_transport_version() returns the version the that was
> 多了个the

已删

2022-06-10 06:49 UTC, jinjiu commented on doc/man3/SSL_CTX_set_quic_method.pod
> +in manner compatible with some versions of BoringSSL.
> 不单单是老版本的BoringSSL，应该是老版本的draft定义的

已改

2022-06-10 06:49 UTC, jinjiu commented on doc/man3/SSL_CTX_set_quic_method.pod
> +SSL_CTX_set_quic_method() and SSL_set_quic_method() configures the QUIC methods.
> configure, not configures

已改

2022-06-10 07:01 UTC, InfoHunter commented
> ntls 需要 quic 么？

好像不需要……

2022-06-10 07:18 UTC, InfoHunter approved these changes

2022-06-10 07:19 UTC, InfoHunter commented
Subject to CIs are green

2022-06-11 03:08 UTC, InfoHunter approved these changes
解决冲突后可merge

2022-06-12 02:23 UTC, jinjiu commented
> 解决冲突后可merge

已解

2022-06-12 02:39 UTC, merged

2022-06-12 02:40 UTC, InfoHunter commented
No need to wait for CI, merged