Support phe algorithm Twisted-EC-ElGamal.
Tongsuo-Project/Tongsuo pull request #320
Opened 2022-11-03 06:35 UTC by wa5i

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [x] 增加或更新了必要的测试用例
- [x] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-11-07 05:25 UTC, dongbeiouba requested changes

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_crypt.c
> +	int ret = 0;
缩进问题

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_crypt.c
> +        if (!EC_POINT_point2oct(key->group, EC_GROUP_get0_generator(key->group),
buf需要改成依据len动态分配，否则可能导致溢出

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_crypt.c
> +    } while (1);
得看看是否可能导致死循环？

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_crypt.c
> +EC_ELGAMAL_CTX *EC_ELGAMAL_CTX_new_ex(EC_KEY *key, int32_t flag)
接口名字有歧义，因为绝大多数以_ex结尾的接口都是在原接口基础上增加参数，OSSL_LIB_CTX *libctx, const char *propq，是否考虑改一下接口名字和实现？例如改成EC_ELGAMAL_CTX_set_flags，（需要先调用EC_ELGAMAL_CTX_new()），

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +    if (ciphertext == NULL || ciphertext->C1 == NULL || ciphertext->C2 == NULL)
挪到函数入口处检查

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +    if (ctx == NULL || ctx->key == NULL || r == NULL || r->C1 == NULL ||
in也需要判空

2022-11-07 05:25 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +        } else if (in[point_len] == 0) {
point_len对应的POINT_CONVERSION_COMPRESSED的EC_POINT，如果EC_POINT编码是POINT_CONVERSION_UNCOMPRESSED，这里这么判断就错了吧。需要处理不同编码方式的情况。

2022-11-09 15:41 UTC, wa5i commented on crypto/ec/ec_elgamal_crypt.c
> +	int ret = 0;
> 缩进问题

已修复

2022-11-14 01:57 UTC, wa5i commented on crypto/ec/ec_elgamal_crypt.c
> +EC_ELGAMAL_CTX *EC_ELGAMAL_CTX_new_ex(EC_KEY *key, int32_t flag)
> 接口名字有歧义，因为绝大多数以_ex结尾的接口都是在原接口基础上增加参数，OSSL_LIB_CTX *libctx, const char *propq，是否考虑改一下接口名字和实现？例如改成EC_ELGAMAL_CTX_set_flags，（需要先调用EC_ELGAMAL_CTX_new()），

鉴于目前还没发布新版本，所以就直接在老接口上加了参数，防止接口过多不好维护，虽然在 master 分支上有一定的兼容性问题，但 ec-elgamal 目前用的不多，应该可控。

2022-11-14 01:58 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +    if (ctx == NULL || ctx->key == NULL || r == NULL || r->C1 == NULL ||
> in也需要判空

已修复

2022-11-14 01:59 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +    if (ciphertext == NULL || ciphertext->C1 == NULL || ciphertext->C2 == NULL)
> 挪到函数入口处检查

已修复

2022-11-14 02:01 UTC, wa5i commented on crypto/ec/ec_elgamal_crypt.c
> +        if (!EC_POINT_point2oct(key->group, EC_GROUP_get0_generator(key->group),
> buf需要改成依据len动态分配，否则可能导致溢出

POINT_CONVERSION_COMPRESSED 的 buf 只有 33个字符，不需要动态分配

2022-11-14 08:14 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +        } else if (in[point_len] == 0) {
> point_len对应的POINT_CONVERSION_COMPRESSED的EC_POINT，如果EC_POINT编码是POINT_CONVERSION_UNCOMPRESSED，这里这么判断就错了吧。需要处理不同编码方式的情况。

已修复

2022-11-23 06:37 UTC, wa5i commented on crypto/ec/ec_elgamal_crypt.c
> +        if (!EC_POINT_point2oct(key->group, EC_GROUP_get0_generator(key->group),
> buf需要改成依据len动态分配，否则可能导致溢出

fixed

2022-11-25 07:16 UTC, dongbeiouba requested changes

2022-11-25 07:16 UTC, dongbeiouba commented on include/openssl/ec.h
> +int EC_POINT_from_string(const EC_GROUP *group, EC_POINT *r,
EC_POINT_from_string()有测试用例吗？

2022-11-25 07:16 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +    plen = EC_POINT_point2oct(ctx->key->group, ciphertext->C2, form, p,
EC_POINT_point2oct()失败时返回0，建议改成plen == 0

2022-11-25 07:16 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +    if (plen != 1 && plen != point_len)
EC_POINT_point2oct()失败时返回0，建议改成plen == 0

2022-11-25 07:16 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_encode.c
> +    if (plen != 1 && plen != point_len)
EC_POINT_point2oct()失败时返回0，建议改成plen == 0

2022-11-25 07:16 UTC, dongbeiouba commented on crypto/ec/ec_elgamal_dlog.c
> +    if (i >= max)
建议增加ERR_raise()

2022-11-25 10:49 UTC, wa5i commented on crypto/ec/ec_elgamal_dlog.c
> +    if (i >= max)
> 建议增加ERR_raise()

fixed

2022-11-25 10:49 UTC, wa5i commented on crypto/ec/ec_elgamal_dlog.c
> +    if (i >= max)
> 建议增加ERR_raise()

fixed

2022-11-25 10:49 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +    if (plen != 1 && plen != point_len)
> EC_POINT_point2oct()失败时返回0，建议改成plen == 0

fixed

2022-11-25 10:49 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +    if (plen != 1 && plen != point_len)
> EC_POINT_point2oct()失败时返回0，建议改成plen == 0

fixed

2022-11-25 10:51 UTC, wa5i commented on crypto/ec/ec_elgamal_encode.c
> +    plen = EC_POINT_point2oct(ctx->key->group, ciphertext->C2, form, p,
> EC_POINT_point2oct()失败时返回0，建议改成plen == 0

fixed

2022-11-25 10:51 UTC, wa5i commented on include/openssl/ec.h
> +int EC_POINT_from_string(const EC_GROUP *group, EC_POINT *r,
> EC_POINT_from_string()有测试用例吗？

已加

2022-11-28 05:51 UTC, dongbeiouba commented
CI有失败 @wa5i

2022-11-29 08:56 UTC, InfoHunter approved these changes

2022-11-29 10:01 UTC, InfoHunter commented
另外Twisted ElGamal在yuque上没有API文档，需要按照API文档的模板填写

2022-11-29 10:04 UTC, wa5i commented
> 另外Twisted ElGamal在yuque上没有API文档，需要按照API文档的模板填写

Twisted ElGamal 跟 EC-ElGamal 用法一样，只是参数不一样，多传了个 flag， 只新增了个API，回头我添加一下文档。

2022-11-29 10:07 UTC, InfoHunter commented
我看 EC ElGamal也没有：https://www.yuque.com/tsdoc/api/pk4xwr 可以一并处理了

2022-11-29 10:08 UTC, dongbeiouba approved these changes

2022-11-29 10:12 UTC, merged