Fix gcc-4.8.5 compile paillier bug
Tongsuo-Project/Tongsuo pull request #322
Opened 2022-11-04 02:08 UTC by wa5i

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-11-06 02:33 UTC, dongbeiouba requested changes

2022-11-06 02:33 UTC, dongbeiouba commented on crypto/paillier/paillier_ctx.c
> +#include <inttypes.h>
如果系统没有inttypes.h文件怎么办？参考一下include/openssl/e_os2.h

2022-11-07 02:15 UTC, wa5i commented on crypto/paillier/paillier_ctx.c
> +#include <inttypes.h>
> 如果系统没有inttypes.h文件怎么办？参考一下include/openssl/e_os2.h

已修改

2022-11-08 01:49 UTC, InfoHunter commented
CI失败了，貌似强制类型转换一下即可

2022-11-08 07:23 UTC, wa5i commented
> CI失败了，貌似强制类型转换一下即可

CI 过了，可以合了 @InfoHunter @dongbeiouba

2022-11-08 07:29 UTC, dongbeiouba approved these changes

2022-11-09 05:43 UTC, merged