The BIGNUM operation supports the method mechanism.
Tongsuo-Project/Tongsuo pull request #323
Opened 2022-11-09 15:40 UTC by wa5i

The BIGNUM operation can be accelerated through the engine module.

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [x] 增加或更新了必要的测试用例
- [x] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-11-10 03:40 UTC, InfoHunter requested changes

2022-11-10 03:40 UTC, InfoHunter commented on crypto/bn/bn_meth.c
> +    OPENSSL_free(meth);
没free meth->name

2022-11-10 03:40 UTC, InfoHunter commented on crypto/bn/bn_meth.c
> +    memcpy(dst, src, sizeof(*dst));
这种copy不合理，因为name没dup，导致不能对dst和src同时free

2022-11-10 04:05 UTC, InfoHunter commented on crypto/bn/bn_meth.c
> +    ret->name = OPENSSL_strdup(name);
OPENSSL_strdup有可能失败，需要判断返回值

2022-11-10 04:06 UTC, InfoHunter commented on crypto/bn/bn_meth.c
> +        ERR_raise(ERR_LIB_EC, EC_R_INCOMPATIBLE_OBJECTS);
不是ERR_LIB_EC，是BN。后面的EC_R也不对

2022-11-10 04:08 UTC, InfoHunter commented on crypto/bn/bn_ctx.c
> +        ERR_raise(ERR_LIB_EC, EC_R_BN_METHOD_NOT_FOUND);
ERR_LIB_BN，不是EC

2022-11-10 04:09 UTC, InfoHunter commented on crypto/bn/bn_ctx.c
> +        ERR_raise(ERR_LIB_EC, ERR_R_ENGINE_LIB);
同下

2022-11-10 04:11 UTC, InfoHunter commented on crypto/engine/tb_bnmeth.c
> +        return 0;
返回0之前需要释放c

2022-11-10 06:48 UTC, wa5i commented on crypto/bn/bn_meth.c
> +    OPENSSL_free(meth);
> 没free meth->name

之前没想好要不要 name，删过一版本，后来才加上，大意了，已修复

2022-11-10 06:48 UTC, wa5i commented on crypto/bn/bn_meth.c
> +    memcpy(dst, src, sizeof(*dst));
> 这种copy不合理，因为name没dup，导致不能对dst和src同时free

已修复

2022-11-10 06:48 UTC, wa5i commented on crypto/bn/bn_meth.c
> +    ret->name = OPENSSL_strdup(name);
> OPENSSL_strdup有可能失败，需要判断返回值

已修复

2022-11-10 06:48 UTC, wa5i commented on crypto/bn/bn_meth.c
> +        ERR_raise(ERR_LIB_EC, EC_R_INCOMPATIBLE_OBJECTS);
> 不是ERR_LIB_EC，是BN。后面的EC_R也不对

copy 代码忘改了，已修复

2022-11-10 06:49 UTC, wa5i commented on crypto/bn/bn_ctx.c
> +        ERR_raise(ERR_LIB_EC, ERR_R_ENGINE_LIB);
> 同下

已修复

2022-11-10 06:49 UTC, wa5i commented on crypto/bn/bn_ctx.c
> +        ERR_raise(ERR_LIB_EC, EC_R_BN_METHOD_NOT_FOUND);
> ERR_LIB_BN，不是EC

已修复

2022-11-10 06:54 UTC, wa5i commented on crypto/engine/tb_bnmeth.c
> +        return 0;
> 返回0之前需要释放c

已修复

2022-11-24 18:59 UTC, InfoHunter approved these changes

2022-11-24 18:59 UTC, merged