Add more bio type support for `SSL_connection_is_ntls`
Tongsuo-Project/Tongsuo pull request #326
Opened 2022-11-17 10:47 UTC by daipingh

在判断连接是否为 ntls 的逻辑中，增加更多类型BIO的支持

##### 风险说明

这个改动**可能**修改 bio 链，使得 `SSL_get_rbio()` 返回的 bio 与 `SSL_set_rbio()` 设置的 bio 不一致

如果某个应用同时满足以下条件，则可能无法正常工作。

- 服务器
- 在 TLS_method 上启用了 NTLS
- 使用除 BIO_TYPE_SOCKET/BIO_TYPE_MEM/BIO_TYPE_BIO/BIO_TYPE_BUFFER 以外的 BIO 类型
- 调用 BIO_write(SSL_get_rbio(s), ...)且没有调用 BIO_flush()，或者对 SSL_get_rbio(s) 返回的 bio 进行断言.

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-11-17 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=326) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=326) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Tongsuo-Project/Tongsuo?pullRequest=326) it.</sub>

2022-11-24 09:50 UTC, dongbeiouba requested changes

2022-11-24 09:50 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                    BIO_set_write_buffer_size(bbio, 1);
我理解没必要设置write buffer size

2022-11-24 09:50 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (ret < 0) {
ret为0的时候呢？应该也是返回return -1吧

2022-11-25 01:18 UTC, InfoHunter commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (BIO_method_type(s->rbio) != BIO_TYPE_BUFFER) {
对于改变原始bio链的行为，可以加个开关，编译的时候让用户选，默认是不开启

2022-11-25 07:03 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (ret < 0) {
BIO_buffer_peek返回-1表示不支持peek，返回0表示可读数据长度为0，所以返回0时标记为继续读数据会更好吧

2022-11-25 07:38 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                    BIO_set_write_buffer_size(bbio, 1);
这个是禁用rbio（bio_f_buffer）的写缓存，防止BIO_write被bio_f_buffer缓存了。

为啥要禁用rbio的写缓存？可以看看下面这个用例场景：

外部程序为SSL设置的rbio为mem类型的bio，而底层连接由应用程序自己接管，当应用程序从底层连接收到数据后，从SSL中获取rbio，然后通过BIO_write将数据写入（期望写入到mem-bio），然后激活SSL以便从rbio中读取数据。

如果不禁用rbio（bio_f_buffer）的写缓存，期望将数据写入到mem-bio，但实际被bio_f_buffer缓存了，会导致后续SSL无法读取到数据

这个参考的是ssl->wbio的，SSL禁用了wbio的读缓存。

2022-11-25 07:43 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (BIO_method_type(s->rbio) != BIO_TYPE_BUFFER) {
SSL针对wbio也套了一层BIO_f_buffer，可以考虑参考wbio的处理方式，但是涉及的代码改动会更多。

2022-11-28 03:36 UTC, dongbeiouba requested changes

2022-11-28 03:36 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (ret < 0) {
我没看到不支持peek时会返回-1，返回的也是0；如果是buffer类型BIO在connect的时候，数据长度应该大于0吧

2022-11-28 03:36 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                    BIO_set_write_buffer_size(bbio, 1);
我看了BIO_set_write_buffer_size()的说明文档，Any attempt to reduce the buffer size below DEFAULT_BUFFER_SIZE is ignored. 你再仔细看看？

2022-11-29 07:31 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                    BIO_set_write_buffer_size(bbio, 1);
我仔细看了一下实现，BIO_set_write_buffer_size(1) 确实会被忽略。。

那就只能假定外部程序不会同时满足以下条件：
- 服务器
- 在 TLS_method 上启用了 NTLS
- 使用除 BIO_TYPE_SOCKET/BIO_TYPE_MEM/BIO_TYPE_BIO/BIO_TYPE_BUFFER 以外的 BIO 类型
- 调用 BIO_write(SSL_get_rbio(s), ...)，并且没有调用 BIO_flush()

2022-11-29 07:32 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (ret < 0) {
核实了一下，不支持时确实会返回-1，已调整代码

2022-11-29 10:23 UTC, dongbeiouba requested changes

2022-11-29 10:23 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                    /* Add a buffer bio to the chain to provide peek support.
注释看上去多余，建议删除

2022-12-01 12:33 UTC, dongbeiouba approved these changes, later dismissed
LGTM

2022-12-09 02:38 UTC, InfoHunter commented
请重新pull下master

2022-12-09 02:38 UTC, InfoHunter commented
ping @daipingh

2023-01-29 10:22 UTC, daipingh commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (BIO_method_type(s->rbio) != BIO_TYPE_BUFFER) {
所以现在来看是否还需要添加编译选项（默认是不开启）？

2023-01-30 06:39 UTC, InfoHunter commented on ssl/statem_ntls/ntls_statem_lib.c
> +                if (BIO_method_type(s->rbio) != BIO_TYPE_BUFFER) {
看起来可以

2023-01-30 06:40 UTC, InfoHunter approved these changes

2023-01-30 08:59 UTC, dongbeiouba approved these changes

2023-01-30 09:00 UTC, merged