Paillier supports setting engine, can support hardware acceleration.
Tongsuo-Project/Tongsuo pull request #331
Opened 2022-12-01 10:41 UTC by wa5i

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [x] 增加或更新了必要的测试用例
- [x] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-12-08 01:39 UTC, InfoHunter submitted a review, later dismissed

2022-12-09 03:12 UTC, dongbeiouba requested changes

2022-12-09 03:12 UTC, dongbeiouba commented on engines/e_bnsoft.c
> +static const char *engine_bnsoft_name = "OpenSSL Test engine support";
OpenSSL -> Tongsuo

2022-12-09 03:12 UTC, dongbeiouba commented on engines/e_bnsoft.c
> +    /* Ensure the bnsoft error handling is set up */
无用的注释，删除吧

2022-12-13 03:30 UTC, wa5i commented on engines/e_bnsoft.c
> +    /* Ensure the bnsoft error handling is set up */
fixed

2022-12-13 03:31 UTC, wa5i commented on engines/e_bnsoft.c
> +static const char *engine_bnsoft_name = "OpenSSL Test engine support";
> OpenSSL -> Tongsuo

fixed

2022-12-13 12:32 UTC, dongbeiouba approved these changes

2022-12-13 12:33 UTC, merged