ShangMi software module, compliance with GM/T 0028
Tongsuo-Project/Tongsuo pull request #338
Opened 2022-12-13 11:37 UTC by dongbeiouba

Add mod app to manage crypto module, including set password, reset module, etc.
Add Hash DRBG, support sha1, sha224, sha256, sha384, sha512, sha512-224, sha512-256, SM3. SM3 DRBG is compliance with GM/T 0105-2021. Add random self test, accoring to GB/T 32915.
Add entropy source, real-time clock(RTC);
Add hmacWithSM3.

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-12-13 14:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=338) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=338) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dongbeiouba<br/>:x: t8m<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Tongsuo-Project/Tongsuo?pullRequest=338) it.</sub>

2022-12-15 08:40 UTC, wa5i requested changes

2022-12-15 08:40 UTC, wa5i commented on crypto/rand/rand_unix.c
> +    entropy_available = rand_acquire_entropy_from_rtc(pool);
没缩进

2022-12-15 08:40 UTC, wa5i commented on include/openssl/rand_drbg.h
> +#endif
与# if没对齐

2022-12-15 08:40 UTC, wa5i commented on crypto/rand/drbg_hash.c
> +    if (drbg->type == NID_sm3)
第345行有判断OPENSSL_NO_SM3，这里没有

2022-12-15 08:40 UTC, wa5i commented on crypto/rand/drbg_hash.c
> +    if (drbg->type == NID_sm3) {
这里没有判断OPENSSL_NO_SM3

2022-12-15 09:29 UTC, dongbeiouba commented on crypto/rand/rand_unix.c
> +    entropy_available = rand_acquire_entropy_from_rtc(pool);
缩进了，是不是看错了

2022-12-15 09:30 UTC, dongbeiouba commented on include/openssl/rand_drbg.h
> +#endif
已修改

2022-12-15 09:31 UTC, dongbeiouba commented on crypto/rand/drbg_hash.c
> +    if (drbg->type == NID_sm3)
这里可以不加OPENSSL_NO_SM3，345行因为需要调用EVP_sm3()

2022-12-15 09:31 UTC, dongbeiouba commented on crypto/rand/drbg_hash.c
> +    if (drbg->type == NID_sm3) {
这里可以不加OPENSSL_NO_SM3，345行因为需要调用EVP_sm3()

2022-12-16 02:14 UTC, wa5i approved these changes
LGTM

2022-12-23 02:30 UTC, InfoHunter approved these changes

2022-12-26 03:46 UTC, merged