s_server supports TLCP SNI test
Tongsuo-Project/Tongsuo pull request #346
Opened 2023-01-16 10:07 UTC by dongbeiouba

s_server add options sign_cert2/sign_key2/enc_cert2/enc_key2 used for setting secondary ctx.

Fix #232

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-01-30 07:03 UTC, InfoHunter requested changes
缺测试用例

2023-02-02 04:04 UTC, dongbeiouba commented
> 缺测试用例

已增加测试用例。

2023-02-06 02:49 UTC, wa5i commented on test/recipes/70-test_ntlssni.t
> +    if disabled("engine") || disabled("dynamic-engine");
这个功能需要 engine？

2023-02-07 03:34 UTC, dongbeiouba commented on test/recipes/70-test_ntlssni.t
> +    if disabled("engine") || disabled("dynamic-engine");
需要，使用的TLSProxy依赖ossltest engine

2023-02-08 06:50 UTC, InfoHunter approved these changes

2023-02-09 02:14 UTC, merged