add force-ntls config option
Tongsuo-Project/Tongsuo pull request #348
Opened 2023-01-23 02:34 UTC by zh-jq

SSL/SSL CTX 增加enable_force_ntls选项，该选项设置后，server端跳过ntls协议检测，直接使用ntls状态机。
对于当前SSL_connection_is_ntls不适用的场景，可由调用方提前进行协议版本检测，通过该选项直接选择使用NTLS协议。

enable_force_ntls true会设置enable_ntls true
enable_ntls false会设置enable_force_ntls false

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件

2023-01-23 02:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=348) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=348) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Tongsuo-Project/Tongsuo?pullRequest=348) it.</sub>

2023-01-28 09:10 UTC, InfoHunter submitted a review, later dismissed

2023-01-29 07:07 UTC, dongbeiouba commented
@zh-jq 能说明一下当前SSL_connection_is_ntls不适用的场景有哪些吗？

2023-01-29 07:26 UTC, iamwwc commented
https://tongsuo.readthedocs.io/zh/latest/Tutorial/SM/ntls/

> 由于国密双证书的握手流程和协议版本号与标准tls流程存在一定的不同，因此我们选择将双证书的实现(代码里命名为ntls)同现有的tls状态机拆分开来，然后在入口处通过对请求的版本号进行识别，然后使其进入正确的状态机。然而比较麻烦的是，openssl的bio体系并没有实现msg_peek的功能，因此目前的实现是通过获取链接的fd，然后通过recv(fd, MSG_PEEK)的形式来获取链接的协议的，造成的困扰是如果你实现了一套非socket形式的bio，则无法使用这个功能，该问题我们后续会视情况进行修复

Rust-openssl使用非socket IO，没有fd可以提供。SSL_connection_is_ntls 会导致tokio Context#waker被丢弃，请求hangup

2023-01-29 07:37 UTC, dongbeiouba commented
> rust-openssl使用非socket IO，没有fd可以提供。SSL_connection_is_ntls 会导致tokio Context#waker被丢弃，请求hangup
对应的BIO_method_type是啥？

2023-01-29 07:38 UTC, zh-jq commented
> @zh-jq 能说明一下当前SSL_connection_is_ntls不适用的场景有哪些吗？

目前我们在做rust封装，基于rust生态已经用量比较大的https://github.com/sfackler/rust-openssl，BIO传递用的AsyncRead + AsyncWrite Generics

2023-01-29 08:48 UTC, zh-jq commented
> 对应的BIO_method_type是啥？

看起来是mem的https://github.com/sfackler/rust-openssl/blob/master/openssl/src/bio.rs

2023-01-29 08:55 UTC, zh-jq commented
看起来 #226 已经支持了。不过仍然还有需求，外侧需要做协议识别的场景仍然可以直接设置该选项，跳过内部的检测

2023-01-29 09:20 UTC, dongbeiouba commented
> 看起来 #226 已经支持了。不过仍然还有需求，外侧需要做协议识别的场景仍然可以直接设置该选项，跳过内部的检测

已经支持的话可以直接close PR。后续有需要的话，可以针对特定场景适配。

2023-01-29 09:29 UTC, zh-jq commented
已经做过协议识别的场景，是否考虑支持通过选项跳过内部的检测？

2023-01-29 09:40 UTC, InfoHunter commented
> 后续有需要的话，可以针对特定场景适配。

@zh-jq 的意思是增加一个手动强制开关强制走NTLS，不涉及BIO类型的支持。我倒是觉得加一个开关更灵活。

2023-01-29 09:56 UTC, zh-jq commented
> 已经做过协议识别的场景，是否考虑支持通过选项跳过内部的检测？

我们自己做协议识别，识别为TLCP的我们走tongsuo处理，识别为TLS的我们就用其他实现了，比如rustls。外部已经处理的情况下，我更倾向于能强制跳过检测。加一个配置项代价大的话，也可以考虑设置enable_ntls = 2来实现这个功能

2023-01-29 13:21 UTC, iamwwc commented
> > 对应的BIO_method_type是啥？
> 
> 看起来是mem的https://github.com/sfackler/rust-openssl/blob/master/openssl/src/bio.rs

https://github.com/sfackler/rust-openssl/blob/78c241f2716320f509f284261ce04812c3751b4f/openssl/src/ssl/bio.rs#L206 没有支持，用的是None BIO

2023-01-30 08:52 UTC, dongbeiouba requested changes

2023-01-30 08:52 UTC, dongbeiouba commented on ssl/ssl_lib.c
> +void SSL_CTX_enable_force_ntls(SSL_CTX *ctx)
SSL_CTX_enable_force_ntls()只设置enable_force_ntls就行，没必要设置enable_ntls，建议和SSL_CTX_disable_force_ntls保持对称。即enable_force_ntls和enable_ntls分开控制，没必要混到一起。

2023-01-30 08:52 UTC, dongbeiouba commented on apps/s_client.c
> +    OPT_NTLS, OPT_ENABLE_NTLS, OPT_ENABLE_FORCE_NTLS,
client并不会进行NTLS  version的检测，OPT_NTLS就意味着发起NTLS握手，没有必要再加OPT_ENABLE_FORCE_NTLS，是不是可以不用修改s_client

2023-01-30 08:52 UTC, dongbeiouba commented on ssl/statem/statem.c
> +    if (s->enable_force_ntls == 1)
客户端并不检测NTLS version，没必要判断enable_force_ntls

2023-01-30 08:52 UTC, dongbeiouba commented on ssl/ssl_conf.c
> +static int cmd_Enable_force_ntls(SSL_CONF_CTX *cctx, const char *value)
需要增加测试用例，测试服务端配置enable_force_ntls的情况，包括握手成功（NTLS - NTLS）和失败（非NTLS - NTLS）。可以在test/ssl-tests/31-ntls.cnf.in增加对应的测试用例。

2023-02-01 06:42 UTC, InfoHunter approved these changes

2023-02-02 05:44 UTC, dongbeiouba approved these changes

2023-02-02 05:46 UTC, dongbeiouba commented
感谢提交PR。

2023-02-02 05:47 UTC, merged

2023-02-02 06:18 UTC, zh-jq commented
@dongbeiouba @InfoHunter 8.4有预期发布时间吗？还是8.3分支再提个PR？目前我们用的8.3.2

2023-02-03 03:30 UTC, InfoHunter commented
8.4预计要推迟到今年夏天。8.3分支原则上不会增加新功能，只修复bug，因此如果此功能不是特别着急，还请等待下8.4的发布。即使合并到8.3分支，也需要等8.3.3发布