SSL_connection_is_ntls改成使用预读方式判断是否为NTLS，而不是peek
Tongsuo-Project/Tongsuo pull request #355
Opened 2023-02-04 18:04 UTC by dongbeiouba

使用直接读取数据的方式，而不是peek，可以更好的适应不同的事件处理方式，
包括ET和LT。同时不用再适配不同类型的bio处理peek数据问题，直接使用
BIO_read()统一处理。

Fix #352

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-02-06 02:12 UTC, InfoHunter submitted a review, later dismissed

2023-02-06 02:12 UTC, InfoHunter commented
可以在CHANGES里加一行

2023-02-06 02:17 UTC, dongbeiouba commented
> 可以在CHANGES里加一行

done

2023-02-06 02:18 UTC, InfoHunter approved these changes, later dismissed

2023-02-06 02:27 UTC, wa5i requested changes

2023-02-06 02:27 UTC, wa5i commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                SSL_AD_INTERNAL_ERROR,
上下没对齐

2023-02-06 02:27 UTC, wa5i commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                SSL_AD_INTERNAL_ERROR,
上下没对齐

2023-02-06 02:27 UTC, wa5i commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                            s->preread_buf,
上下没对齐

2023-02-06 02:38 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                SSL_AD_INTERNAL_ERROR,
Fixed

2023-02-06 02:38 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                SSL_AD_INTERNAL_ERROR,
Fixed

2023-02-06 02:38 UTC, dongbeiouba commented on ssl/statem_ntls/ntls_statem_lib.c
> +                                            s->preread_buf,
Fixed

2023-02-09 02:13 UTC, InfoHunter approved these changes

2023-02-10 06:28 UTC, wa5i approved these changes

2023-02-10 06:28 UTC, merged