Support SM4-NI optimization
Tongsuo-Project/Tongsuo pull request #356
Opened 2023-02-05 11:20 UTC by InfoHunter

SM4-CTR/GCM can be optimized by utilizing AES-NI. It would have a boost on performance at +130% for normal size data blocks. For instance, on 256 byte data blocks, we have:

    118MB/s (Tongsuo-8.3) vs 285MB/s (Tongsuo-8.3 w/SM4NI)

The optimized version is nearly 2.5 times faster of the former one.

This feature requires compilers that have 'x86intrin.h' to get built.

通常情况下8.3-stable分支并不接受新的特性，但是此优化较为重要，因此计划合并进8.3分支。

此功能基于 Markku-Juhani O. Saarinen 的理论：https://github.com/mjosaarinen/sm4ni

This PR resolves #250 

##### Checklist

- [x] 在 https://yuque.com/tsdoc 增加或更新了必要的文档：https://www.yuque.com/tsdoc/ts/eksg4u092ixd349k
- [x] 增加或更新了必要的测试用例
- [x] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-02-05 11:32 UTC, InfoHunter commented
Ping the original author @william-zk for a review

2023-02-06 01:14 UTC, zzl360 commented
could this be assembly language like https://github.com/torvalds/linux/blob/master/arch/x86/crypto/sm4-aesni-avx-asm_64.S and https://github.com/torvalds/linux/blob/master/arch/x86/crypto/sm4-aesni-avx2-asm_64.S since the openssl and Tongsuo use plasm？
another question:as @uudiin mentioned in https://github.com/torvalds/linux/commit/a7ee22ee1445c7fdb00ab80116bb9710ca86a860,cbc decrypto could also be optimized  by this code.
and, maybe we should use this code in https://github.com/Tongsuo-Project/Tongsuo/blob/master/providers/implementations/ciphers/cipher_sm4_gcm_hw.c to be used in sm4_gcm.

2023-02-06 02:49 UTC, InfoHunter commented
> could this be assembly language like https://github.com/torvalds/linux/blob/master/arch/x86/crypto/sm4-aesni-avx-asm_64.S and https://github.com/torvalds/linux/blob/master/arch/x86/crypto/sm4-aesni-avx2-asm_64.S since the openssl and Tongsuo use plasm？

It could be, but pure assembly language is hard to maintain. It's also not easy to find a long-term maintainer if the original author is no long with the project (OpenSSL also suffered from this in the past). Using compiler intrinsics has less problems but will lose independency of build, which I think is acceptable for Tongsuo's scenarios.

> another question:as @uudiin mentioned in https://github.com/torvalds/linux/commit/a7ee22ee1445c7fdb00ab80116bb9710ca86a860 ,cbc decrypt could also be optimized by this code.
and, maybe we should use this code in https://github.com/Tongsuo-Project/Tongsuo/blob/master/providers/implementations/ciphers/cipher_sm4_gcm_hw.c to be used in sm4_gcm.

That file is in master branch and I will work on that later. For CBC decryption, it can be done but with a low priority. TLS 1.3 has dropped CBC mode and we also intend to make SM4 GCM more popular with high perf in both encryption and decryption.

2023-02-06 03:28 UTC, InfoHunter commented
Dead CPU architectures like HP-PA, Alpha and PowerPC are also removed in cross-compile test.

2023-02-07 11:22 UTC, dongbeiouba requested changes

2023-02-07 11:22 UTC, dongbeiouba commented on include/crypto/sm4.h
> +#  include <x86intrin.h>
include需要增加缩进

2023-02-10 03:55 UTC, dongbeiouba approved these changes
LGTM

2023-02-10 04:48 UTC, merged

2023-02-21 13:38 UTC, zzl360 commented on crypto/evp/e_sm4.c
> +        gctx->ctr = (ctr128_f) sm4_ctr128_encrypt_blocks;
should use cpu feature detection

2023-02-21 13:38 UTC, zzl360 commented on crypto/evp/e_sm4.c
> +        gctx->ctr = (ctr128_f) sm4_ctr128_encrypt_blocks;
should add line
if(AESNI_CAPABLE &&  (OPENSSL_ia32cap_P[1]&(1<<(9))))//aesni and ssse3.but may be should use ssse4_1 which is (OPENSSL_ia32cap_P[1]&(1<<(19))

2023-11-15 23:54 UTC, InfoHunter commented on crypto/evp/e_sm4.c
> +        gctx->ctr = (ctr128_f) sm4_ctr128_encrypt_blocks;
It seems this should be added