Added zuc and paillier algorithms to speed automated test script.
Tongsuo-Project/Tongsuo pull request #377
Opened 2023-03-11 15:36 UTC by wa5i

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-03-16 02:45 UTC, wa5i commented
ping @InfoHunter @dongbeiouba

2023-03-16 02:56 UTC, dongbeiouba requested changes

2023-03-16 02:56 UTC, dongbeiouba commented on .github/workflows/speed-test.yml
> +          git checkout master
为啥要切换到master分支？

2023-03-17 02:58 UTC, wa5i commented on .github/workflows/speed-test.yml
> +          git checkout master
> 为啥要切换到master分支？

在 git status --porcelain 之前切换到 master 分支而已，解决目前 CI 报错的问题：
![image](https://user-images.githubusercontent.com/7484739/225801139-550561f0-5d66-44ea-94e2-9218a8b1adcc.png)

2023-03-21 02:13 UTC, dongbeiouba approved these changes
LGTM

2023-03-31 02:31 UTC, InfoHunter approved these changes

2023-03-31 02:33 UTC, merged