Modify the judgment condition of variable i
Tongsuo-Project/Tongsuo pull request #399
Opened 2023-05-01 03:03 UTC by arche8

在punycode_test.c中，第157行i的判断条件有误，应改为i < sizeof(tc->raw) / sizeof(int)

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-05-01 03:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Tongsuo-Project/Tongsuo?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Tongsuo-Project/Tongsuo?pullRequest=399) it.</sub>

2023-05-04 12:34 UTC, dongbeiouba requested changes

2023-05-04 12:34 UTC, dongbeiouba commented on test/punycode_test.c
> +    for (i = 0; i < sizeof(tc->raw) / sizeof(int); i++)
直接用OSSL_NELEM()吧

2023-05-04 13:03 UTC, arche8 commented
已经做出了修改

2023-05-04 13:19 UTC, arche8 commented
已经做出了修改

2023-05-05 02:01 UTC, dongbeiouba approved these changes
LGTM

2023-05-09 08:20 UTC, InfoHunter approved these changes

2023-05-09 08:21 UTC, merged

2023-05-09 08:21 UTC, InfoHunter commented
Merged, thanks for the contribution!