支持OpenHarmony操作系统3.2版本
Tongsuo-Project/Tongsuo pull request #430
Opened 2023-06-14 09:25 UTC by dongbeiouba

OpenHarmony操作系统可以基于铜锁构建。
其中，Huks模块可以使用铜锁作为底层的Engine，提供密钥管理等能力。
同理，对于其他模块，包括certificate_manager等，以及第三方模块都可以依赖铜锁
提供的密码学原语和安全传输协议。

OpenHarmony基于铜锁构建，需要修改构建脚本，主要包括：
使用Tongsuo头文件，//third_party/Tongsuo/include
依赖libcrypto动态库，//third_party/Tongsuo:tongsuo_libcrypto_shared 依赖libssl动态库，//third_party/Tongsuo:tongsuo_libssl_shared

完整的适配文档，请参考铜锁官方文档。

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-06-20 06:52 UTC, InfoHunter commented on prebuilts/README.md
> +## 预构建文件
prebuilts文件太多了，不需要提交到仓库里，否则每次git archive打包代码的时候这些东西也兜打包进去了。每次build之前构建即可

2023-06-20 06:53 UTC, InfoHunter requested changes
提交prebuilts内容不合理，主要是这些东西不需要进入版本控制范围

2023-06-20 08:35 UTC, dongbeiouba commented on prebuilts/README.md
> +## 预构建文件
改成使用压缩包了，构建OpenHarmony时先解压prebuilts.tar.gz

2023-06-21 05:24 UTC, InfoHunter approved these changes

2023-06-21 05:25 UTC, merged