Paillier speed test supports keys of other bit lengths.
Tongsuo-Project/Tongsuo pull request #436
Opened 2023-06-26 03:25 UTC by wa5i

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2023-06-30 05:37 UTC, dongbeiouba requested changes

2023-06-30 05:37 UTC, dongbeiouba commented on apps/speed.c
> +        "paillier_15360",
为啥这里出来个15360？

2023-06-30 05:39 UTC, wa5i commented on apps/speed.c
> +        "paillier_15360",
> 为啥这里出来个15360？

没删干净，我删除一下

2023-06-30 05:41 UTC, wa5i commented on apps/speed.c
> +        "paillier_15360",
已删

2023-06-30 11:12 UTC, dongbeiouba approved these changes
LGTM

2023-07-12 23:58 UTC, InfoHunter approved these changes

2023-07-13 00:10 UTC, merged