Support TLS certificate compression
Tongsuo-Project/Tongsuo pull request #50
Opened 2022-07-13 10:42 UTC by jinjiu

##### Checklist

- [x] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-07-14 08:28 UTC, dongbeiouba requested changes
ssl/statem_ntls/ntls_extensions.c中的ext_defs也需要修改，对应TLSEXT_IDX_compress_certificate的位置增加INVALID_EXTENSION

2022-07-14 08:28 UTC, dongbeiouba commented on doc/man3/SSL_add_cert_compression_alg.pod
> +Copyright 2020-2021 The OpenSSL Project Authors. All Rights Reserved.
Copyright不对

2022-07-14 15:27 UTC, jinjiu commented on doc/man3/SSL_add_cert_compression_alg.pod
> +Copyright 2020-2021 The OpenSSL Project Authors. All Rights Reserved.
已修改

2022-07-14 15:27 UTC, jinjiu commented
> ssl/statem_ntls/ntls_extensions.c中的ext_defs也需要修改，对应TLSEXT_IDX_compress_certificate的位置增加INVALID_EXTENSION

已修复

2022-07-14 16:03 UTC, dongbeiouba approved these changes
LGTM

2022-07-15 02:26 UTC, InfoHunter approved these changes

2022-07-15 02:26 UTC, merged