Add an api to support duplication of SSL_CTX: SSL_CTX_dup
Tongsuo-Project/Tongsuo pull request #52
Opened 2022-07-16 01:30 UTC by jinjiu

##### Checklist

- [ ] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-07-16 21:17 UTC, InfoHunter commented
有内存泄露

2022-07-18 08:15 UTC, jinjiu commented
> 有内存泄露

已修复

2022-07-18 16:38 UTC, dongbeiouba requested changes

2022-07-18 16:38 UTC, dongbeiouba commented on crypto/armcap.c
> +#if 0
为啥注释掉？代码加一下注释吧

2022-07-18 16:38 UTC, dongbeiouba commented on test/babasslapitest.c
> +#if !defined(OPENSSL_NO_TLS1_2) && !defined(OPENSSL_NO_TLS1_1)
建议直接把#if !defined(OPENSSL_NO_TLS1_2) && !defined(OPENSSL_NO_TLS1_1)放到函数test_babassl_ssl_ctx_dup()外面，下同

2022-07-20 09:23 UTC, jinjiu commented on crypto/armcap.c
> +#if 0
> 为啥注释掉？代码加一下注释吧

本地编译器告警，临时代码忘记恢复了

2022-07-20 09:23 UTC, jinjiu commented on test/babasslapitest.c
> +#if !defined(OPENSSL_NO_TLS1_2) && !defined(OPENSSL_NO_TLS1_1)
> 建议直接把#if !defined(OPENSSL_NO_TLS1_2) && !defined(OPENSSL_NO_TLS1_1)放到函数test_babassl_ssl_ctx_dup()外面，下同

已改

2022-07-21 02:41 UTC, merged