Fix coverity issues, resource leaks
Tongsuo-Project/Tongsuo pull request #622
Opened 2024-06-19 15:03 UTC by dongbeiouba

CID: 488393, 471339, 471290, 471289, 471287, 471282, 471281, 471279, 471246, 471237, 471221, 471204, 471196, 471180, 471171, 471169, 471162, 278385, 21756.

##### Checklist

- [ ] 在 https://yuque.com/tsdoc 增加或更新了必要的文档
- [ ] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2024-06-23 21:37 UTC, InfoHunter commented on crypto/ec/ec_lib.c
> +    if (new_r != NULL && *r != new_r)
无需判断new_r是否为空，可减少一次判断

2024-06-23 21:38 UTC, InfoHunter requested changes
EC_POINT_free可以处理输入为空的情况

2024-06-24 02:03 UTC, dongbeiouba commented on crypto/ec/ec_lib.c
> +    if (new_r != NULL && *r != new_r)
Fixed

2024-06-24 02:03 UTC, dongbeiouba commented
> EC_POINT_free可以处理输入为空的情况

Fixed

2024-06-24 07:02 UTC, InfoHunter approved these changes

2024-06-24 07:02 UTC, merged