Support phe algorithm EC-ElGamal.
Tongsuo-Project/Tongsuo pull request #8
Opened 2022-05-26 06:38 UTC by jinjiu

由于 3.0 与 1.1 的一些接口不兼容，所以编译参数 enable-ec_elgamal 需要加上 no-deprecated --api=1.1.1 才能编译通过，后面再添加 3.0 的接口。

##### Checklist

- [ ] 增加或更新了必要的文档（包括readthedocs上）
- [x] 增加或更新了必要的测试用例
- [ ] 对于重要修改，更新了CHANGES文件
- [ ] 当前修改存在对已有API参数或返回值的改变
- [ ] 当前修改存在对旧版本功能的兼容性改变（如网络协议或密码算法）

2022-05-26 06:55 UTC, InfoHunter commented on crypto/ec/ec_elgamal.c
> +/*
新增的涉及license的文件，都改成：

/*
 * Copyright 2022 The Tongsuo Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE
 */

2022-05-26 06:56 UTC, InfoHunter commented on crypto/ec/ec_elgamal.c
> +/*
如果是2021年就存在的文件，那时间就是2021 - 2022，以此类推

2022-05-26 06:56 UTC, InfoHunter commented on crypto/ec/ec_elgamal.c
> +/*
注意：老的OpenSSL自有的文件不需要动

2022-05-26 06:58 UTC, InfoHunter commented on crypto/ec/ec_elgamal.h
> +/*
同上，需修改copyright内容

2022-05-26 06:59 UTC, InfoHunter commented on doc/man3/EC_ELGAMAL_encrypt.pod
> +Copyright 2020-2022 The OpenSSL Project Authors. All Rights Reserved.
改copyright内容，同前面俩文件

2022-05-26 07:00 UTC, InfoHunter commented on test/ec_elgamal_internal_test.c
> +/*
改copyright内容

2022-05-26 07:00 UTC, InfoHunter commented on test/recipes/03-test_internal_ec_elgamal.t
> +# Copyright 2019 The OpenSSL Project Authors. All Rights Reserved.
改copyright

2022-05-26 07:07 UTC, jinjiu commented on crypto/ec/ec_elgamal.c
> +/*
> 新增的涉及license的文件，都改成：
> 
> /*
> 
> * Copyright 2022 The Tongsuo Project Authors. All Rights Reserved.
> * Licensed under the Apache License 2.0 (the "License").  You may not use
> * this file except in compliance with the License.  You can obtain a copy
> * in the file LICENSE in the source distribution or at
> * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE
>   */

ok，我改一下

2022-05-30 02:05 UTC, jinjiu commented
ping @InfoHunter @dongbeiouba

2022-05-30 13:49 UTC, dongbeiouba requested changes

2022-05-30 13:49 UTC, dongbeiouba commented on doc/man3/EC_ELGAMAL_encrypt.pod
> +
#  ifndef OPENSSL_NO_EC_ELGAMAL

2022-05-30 13:49 UTC, dongbeiouba commented on crypto/ec/ec_elgamal.c
> +    if (ciphertext == NULL)
出错时需要记录错误，包括但不限于内存分配失败，例如增加：ERR_raise(ERR_LIB_EC, ERR_R_MALLOC_FAILURE); 下同。

2022-05-31 09:47 UTC, jinjiu commented on crypto/ec/ec_elgamal.c
> +    if (ciphertext == NULL)
> 出错时需要记录错误，包括但不限于内存分配失败，例如增加：ERR_raise(ERR_LIB_EC, ERR_R_MALLOC_FAILURE); 下同。

已修复

2022-05-31 09:47 UTC, jinjiu commented on include/openssl/ec.h
> +int EC_ELGAMAL_decrypt(EC_ELGAMAL_CTX *ctx, int32_t *r, EC_ELGAMAL_CIPHERTEXT *ciphertext);
> cosnt EC_ELGAMAL_CIPHERTEXT *ciphertext

已修复

2022-06-01 02:22 UTC, dongbeiouba approved these changes
LGTM

2022-06-06 01:56 UTC, jinjiu commented
ping @InfoHunter

2022-06-06 07:11 UTC, InfoHunter commented on crypto/ec/ec_elgamal.h
> + * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE
https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE

这个连接再改一下，应该是LICENSE.txt

2022-06-07 02:45 UTC, jinjiu commented on crypto/ec/ec_elgamal.h
> + * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE
> 别的PR里也一并改了

已改

2022-06-07 06:28 UTC, InfoHunter approved these changes

2022-06-07 06:31 UTC, InfoHunter approved these changes

2022-06-07 06:32 UTC, merged